### ISSUE TITLE
jaar needs to be in importable packages, sub and main packages

### ISSUE THREAD

**Issue by jschalk** [jschalk/keg#114]
- [ ] check possible resource: https://www.foundationsafety.com/setuptools
- [ ] learn how create example publishable package. 
- [ ] learn how to use github actions to publish package automatically as part of CI/CD #70 
- [ ] create jaar-road package that contains src/_road files road.py, and finance.py 
- [ ] create jaar-agenda package that imports jaar-road and all src/agenda/ files between agenda.py and tree_metrics.py
- [ ] create jaar-econ package that imports jaar-agenda and all src/econ/ files clerk.py, econ.py, treasury_db_config.json, treasury_sqlstr.py
- [ ] create jaar-world package that imports jaar-econ and all src/world/ files between gift.py and world.py
- [ ] create jaar package that imports jaar-world into the most user friendly directory structure possible.

**Comment by jschalk** [comment]
There are notes how to create a publishable package in the previous ticket #3

**Comment by jschalk** [comment]
@FemiWilliams would you be interested in this?

**Comment by FemiWilliams** [comment]
Yeah, happy to take this on after closing the other ticket.

**Comment by jschalk** [comment]
close for now. May be reopened later.
